### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by Zaseth** [WaddleNinjas/ClubPenuin-HTML5#1]
Hi there.

I stumbled upon your repository and when I downloaded the included ZIP on a VM, it contains code that I've written myself. I don't know who you are, but I don't think I've ever given you permission.

**Comment by WaddleNinjas** [comment]
Hello thank you for the issue @Zaseth I will be taking action on this with my staff team immediately
if there is any questions please reply back.

**Comment by WaddleNinjas** [comment]
Hello thank you for the issue @Zaseth I will be taking action on this with my staff team immediately
if there is any questions please reply back.

**Comment by WaddleNinjas** [comment]
Hello thank you for the issue @Zaseth I will be taking action on this with my staff team immediately
if there is any questions please reply back.

**Comment by Zaseth** [comment]
@WaddleNinjas Thank you. I didn't know if it was appropriate to ask here so I closed it but I'll keep it open. This code is part of CPRewritten
